*** Settings ***
Library  SeleniumLibrary


*** Variables ***
#Dados gerais
${URL}  https://www.kabum.com.br/
${Browser}  chrome

#Dados do teste - Formulario
${FullName}           Caio Mário Aragão
${Telefone}           31955-4330180
${Email}              caio.mario.aragao@marktechbr.com.br
${CPF}                263.869.730-38
${DataNascimento}     15121981
${Senha}              1520@89Ads 

#Dados do teste - Produtos
${Nome_Produto}      Fone de Ouvido Qcy H3 Anc